name: Build

on:
  push:
    branches:
      - '*'
      - '**'
  pull_request:

jobs:
  build:
    name: "Compile"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Compile SCT
        run: php .build/sct.php > .build/bin/UK-DEV.sct

      - name: Compile ESE
        run: php .build/ese.php > .build/bin/UK-DEV.ese

      - name: Compile RWY
        run: cp UK.rwy .build/bin/UK-DEV.rwy

      - name: Upload Build As Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: ".build/bin/"
