name: Validate

on:
  pull_request:

jobs:
  build:
    if: ${{ false }}  # disable for now as we're compiling on branches
    name: "Validate Sectorfile"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Compiler
        run: |
          curl -L --output compiler https://github.com/VATSIM-UK/sector-file-compiler/releases/latest/download/cli-linux-x64
          chmod +x ./compiler

      - name: Validate
        run: |
          ./compiler --config-file compiler.config.json --no-wait --validate
